-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.cvs DROP CONSTRAINT IF EXISTS "user";

ALTER TABLE IF EXISTS public.results DROP CONSTRAINT IF EXISTS user_id;

ALTER TABLE IF EXISTS public.results DROP CONSTRAINT IF EXISTS "cv id";



DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT email UNIQUE (email)
);

DROP TABLE IF EXISTS public.cvs;

CREATE TABLE IF NOT EXISTS public.cvs
(
    id serial,
    user_id serial NOT NULL,
    file_format character varying NOT NULL,
    file_key character varying NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT "unique key" UNIQUE (file_key)
);

DROP TABLE IF EXISTS public.results;

CREATE TABLE IF NOT EXISTS public.results
(
    id serial,
    user_id serial NOT NULL,
    cv_id serial NOT NULL,
    joint_score double precision NOT NULL,
    advice text NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cvs
    ADD CONSTRAINT "user" FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.results
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.results
    ADD CONSTRAINT "cv id" FOREIGN KEY (cv_id)
    REFERENCES public.cvs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;

END;